global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "../nova-alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nova-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s